import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/supabase";
import bcrypt from "bcryptjs";

export async function GET(req: NextRequest) {
  return handleSeed(req);
}

export async function POST(req: NextRequest) {
  return handleSeed(req);
}

async function handleSeed(req: NextRequest) {
  try {
    // 1. Ensure Admin account exists
    let admin = await db.users.findByEmail("admin@gaddvya.com");
    if (!admin) {
      admin = await db.users.findByEmail("admin@railx.com");
    }
    if (!admin) {
      const hashedPassword = await bcrypt.hash("password123", 10);
      await db.users.create({
        name: "GADDVYA Admin",
        email: "admin@gaddvya.com",
        phone: "9876543210",
        password: hashedPassword,
        role: "admin",
        is_email_verified: true,
        is_phone_verified: true,
        gender: "Male",
        dob: "1990-01-01",
        state: "Delhi",
        city: "New Delhi",
        id_proof_type: "Aadhaar Card",
        id_proof_number: "987654321012",
      });
    }

    // 2. Ensure Demo User account exists
    let demoUser = await db.users.findByEmail("user@gaddvya.com");
    if (!demoUser) {
      demoUser = await db.users.findByEmail("user@railx.com");
    }
    if (!demoUser) {
      const hashedPassword = await bcrypt.hash("password123", 10);
      await db.users.create({
        name: "Rahul Sharma",
        email: "user@gaddvya.com",
        phone: "9123456780",
        password: hashedPassword,
        role: "user",
        is_email_verified: true,
        is_phone_verified: true,
        gender: "Male",
        dob: "1995-05-15",
        state: "Maharashtra",
        city: "Mumbai",
        id_proof_type: "Voter ID",
        id_proof_number: "VTR9876543",
      });
    }

    // 3. Populate iconic Indian Railways express network
    const sampleTrainsData = [
      {
        trainNumber: "22436",
        trainName: "Vande Bharat Express",
        trainType: "Vande Bharat",
        from: "New Delhi",
        to: "Varanasi Junction",
        departureTime: "06:00",
        arrivalTime: "14:00",
        duration: "8h 00m",
        totalSeats: 112,
        price: 1750,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "22435",
        trainName: "Vande Bharat Express",
        trainType: "Vande Bharat",
        from: "Varanasi Junction",
        to: "New Delhi",
        departureTime: "15:00",
        arrivalTime: "23:00",
        duration: "8h 00m",
        totalSeats: 112,
        price: 1750,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "12952",
        trainName: "Mumbai Tejas Rajdhani",
        trainType: "Rajdhani Express",
        from: "New Delhi",
        to: "Mumbai Central",
        departureTime: "16:55",
        arrivalTime: "08:35",
        duration: "15h 40m",
        totalSeats: 168,
        price: 2150,
        runsOn: "Daily",
        classes: ["1A", "2A", "3A"],
      },
      {
        trainNumber: "12951",
        trainName: "Mumbai Tejas Rajdhani",
        trainType: "Rajdhani Express",
        from: "Mumbai Central",
        to: "New Delhi",
        departureTime: "17:00",
        arrivalTime: "08:32",
        duration: "15h 32m",
        totalSeats: 168,
        price: 2150,
        runsOn: "Daily",
        classes: ["1A", "2A", "3A"],
      },
      {
        trainNumber: "12302",
        trainName: "Howrah Rajdhani Express",
        trainType: "Rajdhani Express",
        from: "New Delhi",
        to: "Howrah Junction",
        departureTime: "16:50",
        arrivalTime: "09:55",
        duration: "17h 05m",
        totalSeats: 180,
        price: 2280,
        runsOn: "Daily",
        classes: ["1A", "2A", "3A"],
      },
      {
        trainNumber: "12301",
        trainName: "Howrah Rajdhani Express",
        trainType: "Rajdhani Express",
        from: "Howrah Junction",
        to: "New Delhi",
        departureTime: "16:50",
        arrivalTime: "10:05",
        duration: "17h 15m",
        totalSeats: 180,
        price: 2280,
        runsOn: "Daily",
        classes: ["1A", "2A", "3A"],
      },
      {
        trainNumber: "12002",
        trainName: "Bhopal Shatabdi Express",
        trainType: "Shatabdi Express",
        from: "New Delhi",
        to: "Bhopal Junction",
        departureTime: "06:00",
        arrivalTime: "14:40",
        duration: "8h 40m",
        totalSeats: 152,
        price: 1420,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "12001",
        trainName: "Bhopal Shatabdi Express",
        trainType: "Shatabdi Express",
        from: "Bhopal Junction",
        to: "New Delhi",
        departureTime: "15:15",
        arrivalTime: "23:50",
        duration: "8h 35m",
        totalSeats: 152,
        price: 1420,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "20608",
        trainName: "Vande Bharat Express",
        trainType: "Vande Bharat",
        from: "Bengaluru City",
        to: "Chennai Central",
        departureTime: "14:50",
        arrivalTime: "19:20",
        duration: "4h 30m",
        totalSeats: 112,
        price: 1050,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "20607",
        trainName: "Vande Bharat Express",
        trainType: "Vande Bharat",
        from: "Chennai Central",
        to: "Bengaluru City",
        departureTime: "05:50",
        arrivalTime: "10:10",
        duration: "4h 20m",
        totalSeats: 112,
        price: 1050,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "22439",
        trainName: "Vande Bharat Express",
        trainType: "Vande Bharat",
        from: "New Delhi",
        to: "Shri Mata Vaishno Devi Katra",
        departureTime: "06:00",
        arrivalTime: "14:00",
        duration: "8h 00m",
        totalSeats: 112,
        price: 1630,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "22440",
        trainName: "Vande Bharat Express",
        trainType: "Vande Bharat",
        from: "Shri Mata Vaishno Devi Katra",
        to: "New Delhi",
        departureTime: "15:00",
        arrivalTime: "23:00",
        duration: "8h 00m",
        totalSeats: 112,
        price: 1630,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "20901",
        trainName: "Vande Bharat Express",
        trainType: "Vande Bharat",
        from: "Mumbai Central",
        to: "Gandhinagar Capital",
        departureTime: "06:10",
        arrivalTime: "12:25",
        duration: "6h 15m",
        totalSeats: 112,
        price: 1420,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "20902",
        trainName: "Vande Bharat Express",
        trainType: "Vande Bharat",
        from: "Gandhinagar Capital",
        to: "Mumbai Central",
        departureTime: "14:05",
        arrivalTime: "20:25",
        duration: "6h 20m",
        totalSeats: 112,
        price: 1420,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "12004",
        trainName: "Lucknow Shatabdi Express",
        trainType: "Shatabdi Express",
        from: "New Delhi",
        to: "Lucknow Junction",
        departureTime: "06:10",
        arrivalTime: "12:40",
        duration: "6h 30m",
        totalSeats: 140,
        price: 1165,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "12003",
        trainName: "Lucknow Shatabdi Express",
        trainType: "Shatabdi Express",
        from: "Lucknow Junction",
        to: "New Delhi",
        departureTime: "15:30",
        arrivalTime: "22:15",
        duration: "6h 45m",
        totalSeats: 140,
        price: 1165,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "12015",
        trainName: "Ajmer Shatabdi Express",
        trainType: "Shatabdi Express",
        from: "New Delhi",
        to: "Jaipur Junction",
        departureTime: "06:10",
        arrivalTime: "10:40",
        duration: "4h 30m",
        totalSeats: 130,
        price: 980,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "12016",
        trainName: "Ajmer Shatabdi Express",
        trainType: "Shatabdi Express",
        from: "Jaipur Junction",
        to: "New Delhi",
        departureTime: "17:50",
        arrivalTime: "22:40",
        duration: "4h 50m",
        totalSeats: 130,
        price: 980,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "22692",
        trainName: "Bengaluru Rajdhani Express",
        trainType: "Rajdhani Express",
        from: "Hazrat Nizamuddin",
        to: "Bengaluru City",
        departureTime: "20:45",
        arrivalTime: "05:20",
        duration: "32h 35m",
        totalSeats: 190,
        price: 2950,
        runsOn: "Daily",
        classes: ["1A", "2A", "3A"],
      },
      {
        trainNumber: "12434",
        trainName: "Chennai Rajdhani Express",
        trainType: "Rajdhani Express",
        from: "Hazrat Nizamuddin",
        to: "Chennai Central",
        departureTime: "15:35",
        arrivalTime: "20:45",
        duration: "29h 10m",
        totalSeats: 185,
        price: 2890,
        runsOn: "Daily",
        classes: ["1A", "2A", "3A"],
      },
      {
        trainNumber: "12438",
        trainName: "Secunderabad Rajdhani Express",
        trainType: "Rajdhani Express",
        from: "Hazrat Nizamuddin",
        to: "Secunderabad Junction",
        departureTime: "15:35",
        arrivalTime: "13:35",
        duration: "22h 00m",
        totalSeats: 175,
        price: 2450,
        runsOn: "Daily",
        classes: ["1A", "2A", "3A"],
      },
      {
        trainNumber: "12245",
        trainName: "Howrah Yesvantpur Duronto",
        trainType: "Duronto Express",
        from: "Howrah Junction",
        to: "Bengaluru City",
        departureTime: "10:50",
        arrivalTime: "16:00",
        duration: "29h 10m",
        totalSeats: 210,
        price: 2350,
        runsOn: "Daily",
        classes: ["1A", "2A", "3A", "SL"],
      },
      {
        trainNumber: "12046",
        trainName: "Chandigarh Shatabdi Express",
        trainType: "Shatabdi Express",
        from: "Chandigarh",
        to: "New Delhi",
        departureTime: "12:05",
        arrivalTime: "15:20",
        duration: "3h 15m",
        totalSeats: 125,
        price: 785,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
      {
        trainNumber: "12045",
        trainName: "Chandigarh Shatabdi Express",
        trainType: "Shatabdi Express",
        from: "New Delhi",
        to: "Chandigarh",
        departureTime: "19:15",
        arrivalTime: "22:35",
        duration: "3h 20m",
        totalSeats: 125,
        price: 785,
        runsOn: "Daily",
        classes: ["EC", "CC"],
      },
    ];

    await db.trains.bulkUpsert(sampleTrainsData);

    return NextResponse.json({
      success: true,
      message: "Database seeded with sample Indian Railways routes and credentials!",
      accounts: {
        admin: { email: "admin@gaddvya.com", password: "password123", role: "admin" },
        user: { email: "user@gaddvya.com", password: "password123", role: "user" },
      },
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
